version: "3.3"
services:
  cheese_db:
    image: mysql
    container_name: cheese_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - cheese_mysql_backup:/docker-entrypoint-initdb.d
      - cheese_mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: terpusat_v1
      MYSQL_USER: terpusatuser
      MYSQL_PASSWORD: development

  cheese_redis:
    image: bitnami/redis:latest
    container_name: cheese_redis
    ports:
      - 6380:6379
    volumes:
      - cheese_redis_backup:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_PASSWORD=redis_password

  cheese_adminer:
    image: adminer
    container_name: cheese_adminer
    restart: always
    ports:
      - 9100:8080
    environment:
      - ADMINER_DEFAULT_SERVER=cheese_db

  cheese_web:
    depends_on:
      - cheese_db
      - cheese_redis
    image: bitnami/laravel
    container_name: cheese_web
    restart: always
    volumes:
      - ./../:/app
    env_file:
      - ./../.env
    ports:
      - 3000:3000

  cheese_nginx:
    depends_on:
      - cheese_adminer
      - cheese_web
    image: nginx
    container_name: cheese_nginx
    volumes:
      - ./../public/:/var/www/km
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 9200:80
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  cheese_mysql_backup:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/mysql/restore
      o: bind
  cheese_mysql_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/mysql/volume
      o: bind
  cheese_redis_backup:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/redis
      o: bind
