name: Terpusat Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  terpusat-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: |
        echo "Welcome to Terpusat Backend First Action !\n"
        echo "Let do automate....."
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al
